# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: rachel lee
description: >- # this means to ignore newlines until "baseurl:"
  # no description for now
baseurl: "" # the subpath of the site
url: "https://rachelstephlee.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: About
    - name: CV
      slug: /assets/docs/cv_2021.pdf

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: rslee (at) princeton (dot) edu
      link: mailto:rslee@princeton.edu
    - name: Twitter
      value: tweet @ me
      link: http://twitter.com/rachel_s_l
      username: "@rachel_s_l"
  follow:
    - name: LinkedIn
      value: linkedin
      link: http://linkedin.com/in/YourLinkedInUsername
      # hack so that the two follows appear below each other
    - name: empty 
      value: " "
    - name: GitHub
      value: github
      link: http://github.com/YourGitHubUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
